[colors.primary]
background = '#111416'
foreground = '#e2e2e6'

[colors.cursor]
text = '#111416'
cursor = '#e2e2e6'

[colors.vi_mode_cursor]
text = '#111416'
cursor = '#9dcbf7'

[colors.search.matches]
foreground = '#41474e'
background = '#e5b7ee'

[colors.search.focused_match]
foreground = '#41474e'
background = '#9dcbf7'

[colors.footer_bar]
foreground = '#41474e'
background = '#e2e2e6'

[colors.hints.start]
foreground = '#41474e'
background = '#b7c8db'

[colors.hints.end]
foreground = '#41474e'
background = '#b7c8db'

[colors.selection]
text = '#c1c7cf'
background = '#41474e'


[colors.normal]
black   = '#41474e'
red     = '#ffb4ab'
green   = '#9dcbf7'
yellow  = '#b7c8db'
blue    = '#e5b7ee'
magenta = '#9dcbf7'
cyan    = '#b7c8db'
white   = '#e2e2e6'


[colors.bright]
black   = '#8b9199'
red     = '#ffb4ab'
green   = '#9dcbf7'
yellow  = '#b7c8db'
blue    = '#e5b7ee'
magenta = '#9dcbf7'
cyan    = '#b7c8db'
white   = '#e2e2e6'


[colors.dim]
black   = '#41474e'
red     = '#ffb4ab'
green   = '#9dcbf7'
yellow  = '#b7c8db'
blue    = '#e5b7ee'
magenta = '#9dcbf7'
cyan    = '#b7c8db'
white   = '#e2e2e6'
